CREATE DATABASE senac_bd;

USE senac_bd;

CREATE TABLE alunos(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(40) NOT NULL,
    ano INT NOT NULL
);

INSERT INTO alunos (nome, ano)
VALUES ('AMANDA COLLE ZANETTE', 2),
	('AMANDA SILVÉRIO', 2),
    ('ANA JULIA MAFIOLETE MEDEIROS', 2),
    ('ANTHONY MACHADO DE CORDOVA', 2),
    ('ARTHUR CARDOSO', 2),
    ('BERNARDO DO CANTO MARASCHIM', 2),
    ('DANIELA NEGRO CARDOSO', 2),
    ('DAVIH RIBEIRO SILVEIRA', 2),
    ('FERNANDA COSTA DE PRÁ', 2),
    ('GABRIEL DEMSKI DA CONCEIÇÃO', 2),
    ('GIANLUCA CASAGRANDE', 2),
    ('IGOR BASGAL ZEFERINO', 2),
    ('ISABELA ALMEIDA DE QUADROS LUZZI', 2),
    ('ARTHUR GUIMARÃES ALVES', 3),
    ('GRÉGORY PEREIRA BITTENCOURT', 3),
    ('JOÃO ALBERTO BUSCH NASCIMENTO SAADE', 3),
    ('MARIA EDUARDA PIMENTA DE AGUILAR', 3),
    ('PEDRO IVO PESSOA JUNG', 3),
    ('ANGELO AUGUSTO FONTANA COLOMBO', 1),
    ('ANTONIO MENEGHETTI NAPPI', 1),
    ('JHONATAN FERRAREIS VIEIRA', 1),
    ('LUIDY ROECKER DUESSMANN', 1),
    ('RAFAELA PEDROTI BACK', 1);
    
SELECT * FROM alunos;